eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: game-service
  config:
    import: optional:configserver:instead
  cache:
    type: simple
  data:
    mongodb:
      uri: mongodb://localhost:27017/englishTasks

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5450/game_db
    username: admin
    password: root

  flyway:
    locations: classpath:migration

server:
  port: 7550

management:
  tracing:
    sampling:
      probability: 1.0

zipkin:
  tracing:
    endpoint: http://zipkin:9411/api/v2/spans
