eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: game-service
  config:
    import: optional:configserver:instead
  cache:
    type: simple
  data:
    mongodb:
      uri: mongodb://localhost:27017/englishTasks

server:
  port: 7550

management:
  tracing:
    sampling:
      probability: 1.0
