package com.pat.soe.exception;

public enum ExceptionLocations {
    USER_SERVICE_NOT_FOUND,
    USER_SERVICE_VALIDATION,
    USER_DTO_ENTITY_VALIDATION,
    TOKEN_SERVICE_NOT_FOUND,
    TOKEN_SERVICE_VALIDATION,
    TOKEN_SERVICE_FORBIDDEN,
    TOKEN_SERVICE_CONFLICT
}
