server:
  port: 8761

eureka:
  instance:
    hostname: discovery-service
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
   config:
     import: optional:configserver:instead
   application:
     name: discovery-service