spring:
  config:
    import: optional:configserver:instead
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
