eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: task-service
  config:
    import: optional:configserver:instead

    server:
      port: 7550

management:
      tracing:
        sampling:
          probability: 1.0
