eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070

spring:
  application:
    name: player-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spellsofenglish_db
    username: postgres
    password: postgres

management:
  tracing:
    sampling:
      probability: 1.0

